name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.15.0'

    - name: Disable npm proxy (if any)
      run: npm config set proxy null && npm config set https-proxy null

    - name: Use official npm registry
      run: npm config set registry https://registry.npmjs.org/

    - name: Install dependencies with retry
      run: |
        retry() {
          local n=1
          local max=5
          local delay=15
          while true; do
            "$@" && break || {
              if [[ $n -lt $max ]]; then
                ((n++))
                echo "Command failed. Attempt $n/$max:"
                sleep $delay;
              else
                echo "The command has failed after $n attempts."
                return 1
              fi
            }
          done
        }
        retry npm install

    - name: Run tests
      run: npm test

    - name: Build project
      run: npm run build

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
